### ISSUE TITLE
Available for Raspberry Pi?

### ISSUE THREAD

**Issue by monpelaud** [CVMEventi/Countdown#39]
Hi,
Is it possible to use it with a Rasperry Pi5 ?
Best regards

**Comment by cipi1965** [comment]
Hello,
there's not a build for arm64 devices but it should compile without problems

**Comment by monpelaud** [comment]
Thanks for your quick reply.
I'm not an IT guru, is there a guide to compiling the application for Rasperry Pi?

**Comment by monpelaud** [comment]
Hello,
Compiling up to and including version 0.0.34 is ok.
Compiling master version is ko.
`App threw an error during load
TypeError: Cannot read properties of undefined (reading 'forEach')
    at new TimersOrchestrator (/home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:53760:36)
    at new CountdownApp (/home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:52403:35)
    at /home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:78894:22
    at /home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:78897:3
    at Object.<anonymous> (/home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:78900:12)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
[1m[47m[31mA JavaScript error occurred in the main process
[30mUncaught Exception:
TypeError: Cannot read properties of undefined (reading 'forEach')
    at new TimersOrchestrator (/home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:53760:36)
    at new CountdownApp (/home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:52403:35)
    at /home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:78894:22
    at /home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:78897:3
    at Object.<anonymous> (/home/pi/Téléchargements/Countdown-master/.webpack/main/index.js:78900:12)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)[0m
[1m[33m[@vue/compiler-sfc][0m[33m `defineOptions` is a compiler macro and no longer needs to be imported.[0m

[70241:1128/141354.914003:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914186:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914298:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914345:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914412:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914449:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914509:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914545:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914602:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914658:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914729:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914768:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914834:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.914873:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916459:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916547:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916624:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916672:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916747:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916789:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916876:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.916965:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.917034:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.917077:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.917138:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.917175:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.917244:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: Aucun fichier ou dossier de ce type (2)
[70241:1128/141354.917282:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: Aucun fichier ou dossier de ce type (2)
`
Best regards

**Comment by cipi1965** [comment]
Hello, new 1.0 beta supports arm64 build (it should work on RaspberryPiOS 64 bit)
